name: Download

on:
  schedule:
    # every 30 minutes
    - cron: 0/30 * * * *
  workflow_dispatch: {}
jobs:
  update_revision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run downloader script
        run: |
          chmod +x ./download.sh
          ./download.sh
      - name: Commit changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add revisions/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update revisions"
            git push
          else
            echo "No changes to commit"
          fi
